name: CI_action

on:
  push:
    branches: [Development]
  pull_request:
    branches: [Development]

jobs:
  build:  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: worksheet2/my-react-app

      - name: Run the tests
        run: npm test
        working-directory: worksheet2/my-react-app

      - name: Build
        run: npm run build
        working-directory: worksheet2/my-react-app

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman API tests
        run: |
          newman run worksheet2/my-react-app/postman/postman_collection.json 
